// src/routes/componentes/Welcome.svelte
<div class="flex w-full flex-col items-center pt-30">
	<h1 class="lg:text-10 xl:text-12xl text-6xl text-blue-300 md:text-8xl">Welcome</h1>
	<p class=" flex justify-center py-5 text-gray-400">scroll down to see more.</p>
	<div class="mt-20 animate-bounce">
		<span class="flex justify-center text-3xl text-blue-300">&#8595;</span>
	</div>
</div>

// src/components/Welcome.jsx
import React from 'react'

export const Welcome = () => {
  return (
    <div className="space-y-20 bg-black p-20 m-max h-screen flex flex-col items-center">
      <h1 className="text-green-300 text-9xl">Welcome</h1> 
      <p className="text-gray-400">Scroll down</p>
    </div>
  )
}

export default Welcome
